version: "3.9"
services:
  app:
    image: quicklybly/hackaton-back
    container_name: hackaton-back
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

