settings:
  server:
    port: ${SERVER_PORT}
  db:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  port: ${settings.server.port}
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${settings.db.url}
    username: ${settings.db.username}
    password: ${settings.db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt:
  secret: ${SECRET_KEY}
  time-to-expire: 86400000